from enum import Enum

class RunType(Enum):
    RUN_TRAIN_VALIDATION = 1
    RUN_CROSS_VALIDATION = 2
    RUN_GRID_SEARCH      = 3
    RUN_TEST_PREDICTION = 4


# RunType = Enum('RUN_TRAIN_VALIDATION', 'RUN_CROSS_VALIDATION', 'RUN_GRID_SEARCH', 'RUN_TEST_PREDICTION')